AppBundle\Entity\Libro:
    type: entity
    table: libro
    indexes:
        fk_libro_usuario1:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        autor:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        descripcion:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        precio:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        imagenes:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        fechaPublicacion:
            type: datetime
            nullable: false
            column: fecha_publicacion
        titulo:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        isbn:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
